[LMS-457] Test reporter

diff --git a/.github/workflows/test-canvas.yml b/.github/workflows/test-canvas.yml
--- a/.github/workflows/test-canvas.yml
+++ b/.github/workflows/test-canvas.yml
@@ -7,12 +7,12 @@ name: Canvas Extractor - Test
 on:
   pull_request:
     paths:
-      - 'src/canvas-extractor/**'
-      - '!src/canvas-extractor/**/*.md'
+      - "src/canvas-extractor/**"
+      - "!src/canvas-extractor/**/*.md"
   push:
     paths:
-      - 'src/canvas-extractor/**'
-      - '!src/canvas-extractor/**/*.md'
+      - "src/canvas-extractor/**"
+      - "!src/canvas-extractor/**/*.md"
     branches:
       - main
   workflow_dispatch:
@@ -22,44 +22,38 @@ jobs:
     name: Run unit, style, and type checks
     runs-on: ubuntu-20.04
     env:
-        PACKAGE_NAME: canvas-extractor
-        SRC_DIR: src/canvas-extractor
-        LOCK_FILE: src/canvas-extractor/poetry.lock
+      PACKAGE_NAME: canvas-extractor
+      SRC_DIR: src/canvas-extractor
+      LOCK_FILE: src/canvas-extractor/poetry.lock
     steps:
       - name: Checkout code
-        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
-
-      - name: Install Python 3.9
-        uses: actions/setup-python@3105fb18c05ddd93efea5f9e0bef7a03a6e9e7df
-        with:
-          # This one needs to be hard-coded to avoid 3.9.5, due to a bug
-          # in one of the dependencies
-          python-version: '3.9.4'
+        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
 
       - name: Install Poetry
-        uses: Gr1N/setup-poetry@462ac83c852d49e282a1233c4c24c5411696e7c7
+        run: pipx install poetry
 
-      - name: Get virtual env path
-        id: venv-path
-        run: |
-            poetry env use python
-            echo "::set-output name=dir::$(poetry env info -p)"
-        working-directory: ${{ env.SRC_DIR }}
-
-      - name: Setup Dependency Caching
-        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
-        id: cache-venv
+      - name: Install Python 3.9
+        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6 # v3.1.2
         with:
-          path: ${{ steps.venv-path.outputs.dir }}
-          key: ${{ runner.os }}-poetry-${{ hashFiles(env.LOCK_FILE) }}
-          restore-keys: |
-            ${{ runner.os }}-poetry-
+          python-version: "3.9"
+          cache: "poetry"
 
       - name: Run CI Test Task
-        run: python ./eng/build.py ci:test ${{ env.PACKAGE_NAME }}
+        run: |
+          # Next line keeps poetry from trying to use the runner's default Python version
+          pushd ${{ env.SRC_DIR }} && poetry env use "3.9" && popd
+          python ./eng/build.py ci:test ${{ env.PACKAGE_NAME }}
 
       - name: Archive code coverage results
-        uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571
+        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # "v3.1.0"
         with:
           name: code-coverage-report
           path: ${{ env.SRC_DIR }}/htmlcov/
+
+      - name: Test Report
+        uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: PyTests # Name of the check run which will be created
+          path: reports/reports-*.xml # Path to test results
+          reporter: jest-junit # Format of test results
